import { animes as animeDataList } from "@/lib/animeData";

// Définir l'interface pour les animes du catalogue
export interface CatalogueAnime {
  id: string;
  title: string;
  imageUrl?: string; // Optionnel maintenant
  type: "Anime" | "Scans";
  language: "VO" | "VF" | "VF & VO";
  genres?: string[];
}

// Fonction pour obtenir les genres d'un anime par son ID
const getAnimeGenres = (animeId: string): string[] => {
  const anime = animeDataList.find(a => a.id === animeId);
  return anime?.genres || [];
};

export const animes: CatalogueAnime[] = [
    {
        id: "akira",
        title: "Akira",
        imageUrl: "https://m.media-amazon.com/images/M/MV5BM2ZiZTk1ODgtMTZkNS00NTYxLWIxZTUtNWExZGYwZTRjODViXkEyXkFqcGdeQXVyMTE2MzA3MDM@._V1_.jpg",
        type: "Anime",
        language: "VF & VO",
        genres: getAnimeGenres("akira"),
      },
      {
        id: "nagatoro",
        title: "Arrête de me chauffer Nagatoro",
        imageUrl: "https://fr.web.img2.acsta.net/pictures/21/03/24/17/22/3948943.jpg",
        type: "Anime",
        language: "VF & VO",
        genres: getAnimeGenres("nagatoro"),
      },
      {
        id: "welcome-demon-school-teacher",
        title: "Welcome, Demon-School Teacher!",
        imageUrl: "https://m.media-amazon.com/images/M/MV5BY2ZjZmZhN2MtNTk4NC00MmFkLWEwMWEtZGNjOThmMTQ2YjdmXkEyXkFqcGc@._V1_.jpg",
        type: "Anime",
        language: "VO",
        genres: getAnimeGenres("welcome-demon-school-teacher"),
      },
      {
        id: "solo-leveling",
        title: "Solo Leveling",
        imageUrl: "https://img-cdn.thepublive.com/wion/media/post_attachments/files/web-story/900_1600/2024/3/26/1711469910345_sololeveling.jpg",
        type: "Anime",
        language: "VF & VO",
        genres: getAnimeGenres("solo-leveling"),
      },
      {
        id:"clannad",
        title:"Clannad",
        imageUrl:"https://fr.web.img6.acsta.net/pictures/20/09/02/16/06/0799147.jpg",
        type:"Anime",
        language:"VO",
        genres: getAnimeGenres("clannad"),
      },
      {
        id:"gachiakuta",
        title:"Gachiakuta",
        imageUrl:"https://fr.web.img6.acsta.net/img/d5/7b/d57b51b6b84ed66f6dfb47d83aa759a6.jpg",
        type:"Anime",
        language:"VF & VO",
        genres: getAnimeGenres("gachiakuta"),
      },
      {
        id:"fire-force",
        title:"Fire Force",
        imageUrl:"https://fr.web.img5.acsta.net/pictures/19/09/16/16/21/4933552.jpg",
        type:"Anime",
        language:"VF & VO",
        genres: getAnimeGenres("fire-force"),
      },
      {
        id:"horimiya",
        title:"Horimiya",
        imageUrl:"https://imusic.b-cdn.net/images/item/original/447/5022366773447.jpg?anime-2023-horimiya-the-complete-season-dvd&class=scaled&v=1677384610",
        type:"Anime",
        language:"VF & VO",
        genres: getAnimeGenres("horimiya"),
      },
      {
        id: "classroom-of-the-elite",
        title: "Classroom of the Elite",
        imageUrl: "https://m.media-amazon.com/images/M/MV5BMDg3MGVhNWUtYTQ2NS00ZDdiLTg5MTMtZmM5MjUzN2IxN2I4XkEyXkFqcGc@._V1_.jpg",
        type: "Anime",
        language: "VF & VO",
        genres: getAnimeGenres("classroom-of-the-elite"),
      },
      {
        id: "unnamed-memory",
        title: "Unnamed Memory",
        imageUrl: "https://m.media-amazon.com/images/M/MV5BY2Q5NTRiYTgtZjJmOS00YjQ0LWE2MmQtMjE5MmM3ODQ5ZDg2XkEyXkFqcGc@._V1_.jpg",
        type: "Anime",
        language: "VO",
        genres: getAnimeGenres("unnamed-memory"),
      },
      {
        id: "failure-skill-nut-master",
        title: "Failure Skill 'Nut Master'",
        imageUrl: "https://m.media-amazon.com/images/M/MV5BNDQ2MTY2YTEtOWI5ZS00YTFhLTg5YWYtMzkwYTA5NjM5NTIxXkEyXkFqcGc@._V1_FMjpg_UY452_.jpg 319w, https://m.media-amazon.com/images/M/MV5BNDQ2MTY2YTEtOWI5ZS00YTFhLTg5YWYtMzkwYTA5NjM5NTIxXkEyXkFqcGc@._V1_FMjpg_UY678_.jpg 479w, https://m.media-amazon.com/images/M/MV5BNDQ2MTY2YTEtOWI5ZS00YTFhLTg5YWYtMzkwYTA5NjM5NTIxXkEyXkFqcGc@._V1_FMjpg_UY337_.jpg 238w, https://m.media-amazon.com/images/M/MV5BNDQ2MTY2YTEtOWI5ZS00YTFhLTg5YWYtMzkwYTA5NjM5NTIxXkEyXkFqcGc@._V1_FMjpg_UX707_.jpg 707w, https://m.media-amazon.com/images/M/MV5BNDQ2MTY2YTEtOWI5ZS00YTFhLTg5YWYtMzkwYTA5NjM5NTIxXkEyXkFqcGc@._V1_FMjpg_UY1000_.jpg 707w",
        type: "Anime",
        language: "VO",
        genres: getAnimeGenres("failure-skill-nut-master"),
      },
      {
        id: "amagami-san-chi-no-enmusubi",
        title: "Amagami-san Chi no Enmusubi",
        imageUrl: "https://otakulevel10.fr/wp-content/uploads/2025/04/Amagami-Sister-saison-2.jpg",
        type: "Anime",
        language: "VF & VO",
        genres: getAnimeGenres("amagami-san-chi-no-enmusubi"),
      },
      {
        id: "yofukashi-no-uta",
        title: "Call of the Night",
        imageUrl: "https://fr.web.img3.acsta.net/pictures/22/07/04/14/30/5500974.jpg",
        type: "Anime",
        language: "VF & VO",
        genres: getAnimeGenres("yofukashi-no-uta"),
      },
      {
        id: "demon-slayer",
        title: "Demon Slayer",
        imageUrl: "https://fr.web.img6.acsta.net/pictures/19/09/18/13/46/0198270.jpg",
        type: "Anime",
        language: "VF & VO",
        genres: getAnimeGenres("demon-slayer"),
      },
      {
        id: "jujutsu-kaisen",
        title: "Jujutsu Kaisen",
        imageUrl: "https://fr.web.img3.acsta.net/pictures/20/09/14/10/31/4875617.jpg",
        type: "Anime",
        language: "VF & VO",
        genres: getAnimeGenres("jujutsu-kaisen"),
      },
      {
        id: "akudama-drive",
        title: "Akudama Drive",
        imageUrl: "https://upload.wikimedia.org/wikipedia/en/thumb/3/36/Akudama_Drive.jpg/250px-Akudama_Drive.jpg",
        type: "Anime",
        language: "VF & VO",
        genres: getAnimeGenres("akudama-drive"),
      },
      {
        id: "kuroko-no-basket",
        title: "Kuroko no Basket",
        imageUrl: "https://images.justwatch.com/poster/181383869/s718/kuroko-no-basket.jpg",
        type: "Anime",
        language: "VF & VO",
        genres: getAnimeGenres("kuroko-no-basket"),
      },
      {
        id: "vinland-saga",
        title: "Vinland Saga",
        imageUrl: "https://fr.web.img4.acsta.net/pictures/19/09/16/17/09/4903250.jpg",
        type: "Anime",
        language: "VF & VO",
        genres: getAnimeGenres("vinland-saga"),
      },
      {
        id: "death-note",
        title: "Death Note",
        imageUrl: "https://m.media-amazon.com/images/M/MV5BNjRiNmNjMmMtN2U2Yi00ODgxLTk3OTMtMmI1MTI1NjYyZTEzXkEyXkFqcGdeQXVyNjAwNDUxODI@._V1_.jpg",
        type: "Anime",
        language: "VF & VO",
        genres: getAnimeGenres("death-note"),
      },
      {
        id: "frieren",
        title: "Frieren",
        imageUrl: "https://sm.ign.com/ign_fr/screenshot/default/unnamed_qjuy.jpg",
        type: "Anime",
        language: "VF & VO",
        genres: getAnimeGenres("frieren"),
      },
      {
        id: "toradora",
        title: "Toradora!",
        imageUrl: "https://mediaproxy.tvtropes.org/width/1200/https://static.tvtropes.org/pmwiki/pub/images/toradora.png",
        type: "Anime",
        language: "VF & VO",
        genres: getAnimeGenres("toradora"),
      },
      {
        id: "kaguya-sama",
        title: "Kaguya-sama: Love is War",
        imageUrl: "https://fr.web.img3.acsta.net/pictures/20/04/08/16/07/4929472.jpg",
        type: "Anime",
        language: "VF & VO",
        genres: getAnimeGenres("kaguya-sama"),
      },
      {
        id: "your-name",
        title: "Your Name",
        imageUrl: "https://m.media-amazon.com/images/M/MV5BODRmZDVmNzUtZDA4ZC00NjhkLWI2M2UtN2M0ZDIzNDcxYThjL2ltYWdlXkEyXkFqcGdeQXVyNTk0MzMzODA@._V1_.jpg",
        type: "Anime",
        language: "VF & VO",
        genres: getAnimeGenres("your-name"),
      },
      {
        id: "rent-a-girlfriend",
        title: "Rent-a-Girlfriend",
        imageUrl: "https://www.myutaku.com/media/anime/poster/346502.jpg",
        type: "Anime",
        language: "VF & VO",
        genres: getAnimeGenres("rent-a-girlfriend"),
      },
      {
        id: "quintessential-quintuplets",
        title: "The Quintessential Quintuplets",
        imageUrl: "https://m.media-amazon.com/images/M/MV5BODhmMGJjMjQtNDMzNi00ZTJmLWE4ZTItM2YwYjRlZWM5OWMxXkEyXkFqcGc@._V1_.jpg",
        type: "Anime",
        language: "VO",
        genres: getAnimeGenres("quintessential-quintuplets"),
      },
      {
        id: "weathering-with-you",
        title: "Weathering with You",
        imageUrl: "https://m.media-amazon.com/images/I/91IWdBo4TnL._UF894,1000_QL80_.jpg",
        type: "Anime",
        language: "VF & VO",
        genres: getAnimeGenres("weathering-with-you"),
      },
      {
        id: "domestic-girlfriend",
        title: "Domestic Girlfriend",
        imageUrl: "https://m.media-amazon.com/images/M/MV5BYmQyNWI1ZTgtMTgzNC00ZGIyLTg3NWMtZmM2ZjMzNTNjOTU5XkEyXkFqcGc@._V1_FMjpg_UX1000_.jpg",
        type: "Anime",
        language: "VO",
        genres: getAnimeGenres("domestic-girlfriend"),
      },
      {
        id: "golden-time",
        title: "Golden Time",
        imageUrl: "https://m.media-amazon.com/images/M/MV5BNGI0YjdmNGYtZTQ0OC00OWUzLTg2NWMtMjFhNGI1Y2IxNzdmXkEyXkFqcGc@._V1_.jpg",
        type: "Anime",
        language: "VO",
        genres: getAnimeGenres("golden-time"),
      },
      {
        id: "oregairu",
        title: "OreGairu",
        imageUrl: "https://adala-news.fr/wp-content/uploads/2020/02/Oregairu-Saison-3-anime-image.png",
        type: "Anime",
        language: "VO",
        genres: getAnimeGenres("oregairu"),
      },
      {
        id: "Silent-voice",
        title: "Silent Voice",
        imageUrl: "https://fr.web.img3.acsta.net/pictures/18/07/13/11/32/3961973.jpg",
        type: "Anime",
        language: "VF & VO",
        genres: getAnimeGenres("Silent-voice"),
      },
      {
        id: "365-days-to-the-wedding",
        title: "365 Days to the Wedding",
        imageUrl: "https://fr.web.img6.acsta.net/img/c1/7a/c17af00afe845e138265cdf4dc445720.jpg",
        type: "Anime",
        language: "VO",
        genres: getAnimeGenres("365-days-to-the-wedding"),
      },
      {
        id: "nana",
        title: "NANA",
        imageUrl: "https://m.media-amazon.com/images/M/MV5BYjRmOWJmMDgtYjBjMS00OTg1LWJmZTItZTY2MjJlODgxNmUwXkEyXkFqcGc@._V1_FMjpg_UX1000_.jpg",
        type: "Anime",
        language: "VF & VO",
        genres: getAnimeGenres("nana"),
      },
      {
        id: "re-zero",
        title: "Re:Zero - Starting Life in Another World",
        imageUrl: "https://adala-news.fr/wp-content/uploads/2024/11/ReZERO-Starting-Life-in-Another-World-Saison-3-counterattack.jpg",
        type: "Anime",
        language: "VF & VO",
        genres: getAnimeGenres("re-zero"),
      },
      {
        id:"Cyberpunk-Edgerunners",
        title: "Cyberpunk Edgerunners",
        imageUrl: "https://fr.web.img4.acsta.net/pictures/22/06/09/09/16/1463272.jpg",
        type: "Anime",
        language: "VF & VO",
        genres: getAnimeGenres("cyberpunk-edgerunners"),
      },
      {
        id: "tokyo-ghoul",
        title: "Tokyo Ghoul",
        imageUrl: "https://m.media-amazon.com/images/M/MV5BZWI2NzZhMTItOTM3OS00NjcyLThmN2EtZGZjMjlhYWMwODMzXkEyXkFqcGc@._V1_FMjpg_UX1000_.jpg",
        type: "Anime",
        language: "VF & VO",
        genres: getAnimeGenres("tokyo-ghoul"),
      },
      {
        id: "chainsaw-man",
        title: "Chainsaw Man",
        imageUrl: "https://fr.web.img3.acsta.net/pictures/22/08/01/10/00/1492791.jpg",
        type: "Anime",
        language: "VF & VO",
        genres: getAnimeGenres("chainsaw-man"),
      },
      {
        id: "ragna-crimson",
        title: "Ragna Crimson",
        imageUrl: "https://fr.web.img6.acsta.net/pictures/23/09/29/09/01/0704302.jpg",
        type: "Anime",
        language: "VO",
        genres: getAnimeGenres("ragna-crimson"),
      },
      {
        id: "tsukimichi-moonlit-fantasy",
        title: "Tsukimichi - Moonlit Fantasy",
        imageUrl: "https://fr.web.img5.acsta.net/pictures/21/07/05/14/43/1726486.jpg",
        type: "Anime",
        language: "VO",
        genres: getAnimeGenres("tsukimichi-moonlit-fantasy"),
      },
      {
        id: "shingeki-no-kyojin",
        title: "Attack on Titan",
        imageUrl: "https://fr.web.img6.acsta.net/pictures/20/12/28/10/24/5603983.jpg",
        type: "Anime",
        language: "VF & VO",
        genres: getAnimeGenres("attack-on-titan"),
      },
      {
        id: "86-eighty-six",
        title: "86 EIGHTY-SIX",
        imageUrl: "https://fr.web.img6.acsta.net/pictures/21/04/06/18/19/5235708.jpg",
        type: "Anime",
        language: "VF & VO",
        genres: getAnimeGenres("86-eighty-six"),
      },
      {
        id: "akame-ga-kill",
        title: "Akame ga Kill!",
        imageUrl: "https://cdn.myanimelist.net/images/anime/1429/95946.jpg",
        type: "Anime",
        language: "VO",
        genres: getAnimeGenres("akame-ga-kill"),
      },
      {
        id: "aldnoah-zero",
        title: "Aldnoah.Zero",
        imageUrl: "https://m.media-amazon.com/images/M/MV5BOWFkZjdmMzgtMzM0MC00YTA0LWI3Y2YtZmNiOTk4OTE2OTUwXkEyXkFqcGc@._V1_FMjpg_UX1000_.jpg",
        type: "Anime",
        language: "VO",
        genres: getAnimeGenres("aldnoah-zero"),
      },
      {
        id: "ajin",
        title: "Ajin",
        imageUrl: "https://www.manga-news.com/public/images/series/ajin-1-glenat.webp",
        type: "Anime",
        language: "VF & VO",
        genres: getAnimeGenres("ajin"),
      },
      {
        id: "air-gear",
        title: "Air Gear",
        imageUrl: "https://m.media-amazon.com/images/M/MV5BMjg4NDc4NjctOTg0ZC00NDU0LWE3ZmQtNTQ2NWQ2MzMyYjZmXkEyXkFqcGc@._V1_QL75_UY281_CR2,0,190,281_.jpg",
        type: "Anime",
        language: "VF & VO",
        genres: getAnimeGenres("air-gear"),
      },
      {
        id: "aharen-san-wa-hakarenai",
        title: "Aharen-san wa Hakarenai",
        imageUrl: "https://fr.web.img2.acsta.net/pictures/22/03/31/09/46/1204786.jpg",
        type: "Anime",
        language: "VO",
        genres: getAnimeGenres("aharen-san-wa-hakarenai"),
      },
      {
        id: "aho-girl",
        title: "Aho Girl",
        imageUrl: "https://m.media-amazon.com/images/M/MV5BOWRkMjEyNDAtZTg0Ny00YzU0LWIwYjItY2EyZjQ5ZTdhNDFmXkEyXkFqcGc@._V1_.jpg",
        type: "Anime",
        language: "VO",
        genres: getAnimeGenres("aho-girl"),
      },
      {
        id: "akatsuki-no-yona",
        title: "Yona of the Dawn",
        imageUrl: "https://fr.web.img6.acsta.net/pictures/20/03/06/17/37/4676109.jpg",
        type: "Anime",
        language: "VO",
        genres: getAnimeGenres("akatsuki-no-yona"),
      },
      {
        id: "91-days",
        title: "91 Days",
        imageUrl: "https://fr.web.img5.acsta.net/pictures/20/08/27/14/04/0312906.jpg",
        type: "Anime",
        language: "VO",
        genres: getAnimeGenres("91-days"),
      },
      {
        id: "absolute-duo",
        title: "Absolute Duo",
        imageUrl: "https://image.tmdb.org/t/p/original/reoZZ94M0nDL7SGstuChqbLlhNT.jpg",
        type: "Anime",
        language: "VO",
        genres: getAnimeGenres("absolute-duo"),
      },
      {
        id: "a-couple-of-cuckoos",
        title: "A Couple of Cuckoos",
        imageUrl: "https://m.media-amazon.com/images/M/MV5BYWY3MjQ3OTEtMmEwYi00NTYxLWE4ZWQtZWE5YWY1OTE4MDZlXkEyXkFqcGc@._V1_FMjpg_UX1000_.jpg",
        type: "Anime",
        language: "VF & VO",
        genres: getAnimeGenres("a-couple-of-cuckoos"),
      },
      {
        id: "slam-dunk",
        title: "Slam Dunk",
        imageUrl: "https://fr.web.img3.acsta.net/pictures/23/04/18/18/46/1142239.jpg",
        type: "Anime",
        language: "VO",
        genres: getAnimeGenres("slam-dunk"),
      },
      {
        id: "shirobako",
        title: "Shirobako",
        imageUrl: "https://m.media-amazon.com/images/I/81AFkgbK58L._UF894,1000_QL80_.jpg",
        type: "Anime",
        language: "VO",
        genres: getAnimeGenres("shirobako"),
      },
      {
        id: "skip-to-loafer",
        title: "Skip to Loafer",
        imageUrl: "https://m.media-amazon.com/images/M/MV5BMTI3MmJmZmMtMTNkZi00Nzk3LTk5MDUtZmUzMGRlNDFkZmE5XkEyXkFqcGc@._V1_FMjpg_UX1000_.jpg",
        type: "Anime",
        language: "VO",
        genres: getAnimeGenres("skip-to-loafer"),
      },
      {
        id: "shingeki-no-bahamut",
        title: "Shingeki no Bahamut",
        imageUrl: "https://m.media-amazon.com/images/M/MV5BODlhNzBjZjgtOTk4OC00ZTFiLWJkOWItMzQ0ZTY5MGZmMDI4XkEyXkFqcGc@._V1_FMjpg_UX1000_.jpg",
        type: "Anime",
        language: "VF & VO",
        genres: getAnimeGenres("shingeki-no-bahamut"),
      },
      {
        id: "somali-to-mori-no-kamisama",
        title: "Somali to Mori no Kamisama",
        imageUrl: "https://m.media-amazon.com/images/M/MV5BMGI5NzcyYmItNjI1ZS00YWU4LWE1ODYtYmZhN2E1YmU1MTk4XkEyXkFqcGc@._V1_.jpg",
        type: "Anime",
        language: "VO",
        genres: getAnimeGenres("somali-to-mori-no-kamisama"),
      },
      {
        id: "3d-kanojo",
        title: "3D Kanojo",
        imageUrl: "https://m.media-amazon.com/images/M/MV5BYzQ4ZTUzM2UtMzg5MS00MjliLTgzNWYtZTBkYjBkMDA3ZWVhXkEyXkFqcGc@._V1_.jpg",
        type: "Anime",
        language: "VO",
        genres: getAnimeGenres("3d-kanojo"),
      },
      {
        id: "acca-13-ku-kansatsu-ka",
        title: "ACCA: 13-ku Kansatsu-ka",
        imageUrl: "https://m.media-amazon.com/images/M/MV5BM2Y5NmNkY2ItNTlkMi00YzYzLTgzYjctMjRhMThlMWE3NGE2XkEyXkFqcGc@._V1_FMjpg_UX1000_.jpg",
        type: "Anime",
        language: "VO",
        genres: getAnimeGenres("acca-13-ku-kansatsu-ka"),
      },
      {
        id: "acchi-kocchi",
        title: "Acchi Kocchi",
        imageUrl: "https://m.media-amazon.com/images/M/MV5BMTQzYmRjYTktOWQ3OS00NWM3LTk2ZjctYmYzMDEwM2ZjNDAwXkEyXkFqcGc@._V1_.jpg",
        type: "Anime",
        language: "VO",
        genres: getAnimeGenres("acchi-kocchi"),
      },
      {
        id: "shirayuki-aux-cheveux-rouges",
        title: "Shirayuki-hime",
        imageUrl: "https://www.gaming-family.com/wp-content/uploads/daisuki/2016/05/Akagami-no-Shirayuki-hime-01-724x1023.jpg",
        type: "Anime",
        language: "VO",
        genres: getAnimeGenres("shirayuki-aux-cheveux-rouges"),
      },
      {
        id: "shinigami-bocchan-to-kuro-maid",
        title: "Shinigami Bocchan to Kuro Maid",
        imageUrl: "https://cdn-eu.anidb.net/images/main/300788.jpg",
        type: "Anime",
        language: "VO",
        genres: getAnimeGenres("shinigami-bocchan-to-kuro-maid"),
      },
      {
        id: "sk8-the-infinity",
        title: "SK8 the Infinity",
        imageUrl: "https://m.media-amazon.com/images/M/MV5BMjA1YzRjYjAtZDEwZC00NTVkLTk2MWUtYzNmNzcxMDhhMWMwXkEyXkFqcGc@._V1_.jpg",
        type: "Anime",
        language: "VF & VO",
        genres: getAnimeGenres("sk8-the-infinity"),
      },
      {
        id: "soul-eater",
        title: "Soul Eater",
        imageUrl: "",
        type: "Anime",
        language: "VF & VO",
        genres: getAnimeGenres("soul-eater"),
      },
      {
        id: "my-dress-up-darling",
        title: "My Dress-Up Darling",
        imageUrl: "https://m.media-amazon.com/images/M/MV5BYmJhYjgzYTQtMzMxYi00NTkyLWI2MWItNTgxNjk1NzU0YmQzXkEyXkFqcGc@._V1_.jpg",
        type: "Anime",
        language: "VF & VO",
        genres: getAnimeGenres("my-dress-up-darling"),
      },
      {
        id: "silent-witch",
        title: "Silent Witch",
        imageUrl: "https://upload.wikimedia.org/wikipedia/en/9/92/Secrets_of_the_Silent_Witch_light_novel_volume_1_cover.jpg",
        type: "Anime",
        language: "VO",
        genres: getAnimeGenres("silent-witch"),
      },
      {
        id: "shy",
        title: "Shy",
        imageUrl: "https://upload.wikimedia.org/wikipedia/en/3/3e/SHYVolume1.jpg",
        type: "Anime",
        language: "VO",
        genres: getAnimeGenres("shy"),
      },
      {
        id: "16bit-sensation-another-layer",
        title: "16bit Sensation: Another Layer",
        imageUrl: "https://m.media-amazon.com/images/M/MV5BNjA4ZjU5YmQtMjIxZC00YWU4LTlmZmQtZmM1ZWYwMzdmNjE5XkEyXkFqcGc@._V1_FMjpg_UX1000_.jpg",
        type: "Anime",
        language: "VO",
        genres: getAnimeGenres("16bit-sensation-another-layer"),
      },
      {
        id: "dandadan",
        title: "Dandadan",
        imageUrl: "https://fr.web.img6.acsta.net/img/34/d5/34d559cbab6cd1245e84d812d9056ef2.jpg",
        type: "Anime",
        language: "VO",
        genres: getAnimeGenres("dandadan"),
      },
      {
        id: "blue-archive-the-animation",
        title: "Blue Archive The Animation",
        imageUrl: "https://m.media-amazon.com/images/M/MV5BZjllMWNiNmEtNzlkZS00YjZmLWExZGQtMjg5OTUyYjA3MzEzXkEyXkFqcGc@._V1_.jpg",
        type: "Anime",
        language: "VO",
        genres: getAnimeGenres("blue-archive-the-animation"),
      },
      {
        id: "a-galaxy-next-door",
        title: "A Galaxy Next Door",
        imageUrl: "https://fr.web.img2.acsta.net/pictures/23/03/22/17/03/3586652.jpg",
        type: "Anime",
        language: "VO",
        genres: getAnimeGenres("a-galaxy-next-door"),
      },
      {
        id: "7th-time-loop-the-villainess-enjoys-a-carefree-life-married-to-her-worst-enemy",
        title: "7th Time Loop",
        imageUrl: "https://m.media-amazon.com/images/M/MV5BYTMyZGJhNDktMzdkNi00MGY1LWFiMDgtMjhhMzQ2MTQyYWIxXkEyXkFqcGc@._V1_.jpg",
        type: "Anime",
        language: "VO",
        genres: getAnimeGenres("7th-time-loop-the-villainess-enjoys-a-carefree-life-married-to-her-worst-enemy"),
      },
      {
        id: "bocchi-the-rock",
        title: "Bocchi the Rock!",
        imageUrl: "https://m.media-amazon.com/images/M/MV5BOTJiNjMyYzQtODA3YS00YjNjLWExYzYtMGI1YWVlZjY2YWU4XkEyXkFqcGc@._V1_.jpg",
        type: "Anime",
        language: "VF & VO",
        genres: getAnimeGenres("bocchi-the-rock"),
      },
      {
        id: "one-piece",
        title: "One Piece",
        imageUrl: "https://external-preview.redd.it/one-piece-anime-going-on-break-returning-april-2025-v0-eAfnmFuSst07MCSMmNjQ8jHWr3i3CmWsYgbs057RedE.jpg?width=640&crop=smart&auto=webp&s=3156f60eab0be615b09d2d9f329120d45f0c0ade",
        type: "Anime",
        language: "VF & VO",
        genres: getAnimeGenres("one-piece"),
      },
      {
        id: "naruto",
        title: "Naruto",
        imageUrl: "https://cdn.myanimelist.net/images/anime/13/17405.jpg",
        type: "Anime",
        language: "VF & VO",
        genres: getAnimeGenres("naruto"),
      },
      {
        id: "fullmetal-alchemist-brotherhood",
        title: "Fullmetal Alchemist: Brotherhood",
        imageUrl: "https://fr.web.img6.acsta.net/pictures/19/07/29/15/50/2364027.jpg",
        type: "Anime",
        language: "VF & VO",
        genres: getAnimeGenres("fullmetal-alchemist-brotherhood"),
      },
      {
        id: "kaiju-n8",
        title: "Kaiju No. 8",
        imageUrl: "https://fr.web.img6.acsta.net/img/77/07/77079c0a800097522800816954373303.jpg",
        type: "Anime",
        language: "VF & VO",
        genres: getAnimeGenres("kaiju-n8"),
      },
      {
        id: "angel-beats",
        title: "Angel Beats!",
        imageUrl: "https://fr.web.img6.acsta.net/pictures/19/07/11/16/29/4922111.jpg",
        type: "Anime",
        language: "VF & VO",
        genres: getAnimeGenres("angel-beats"),
      },
      {
        id: "assassination-classroom",
        title: "Assassination Classroom",
        imageUrl: "https://m.media-amazon.com/images/M/MV5BZjBkYmRiOTAtY2IwOS00ZWU3LTk3YjItNjMzYWZiMDE1MjcyXkEyXkFqcGc@._V1_FMjpg_UX1000_.jpg",
        type: "Anime",
        language: "VF & VO",
        genres: getAnimeGenres("assassination-classroom"),
      },
      {
        id: "beastars",
        title: "Beastars",
        imageUrl: "https://fr.web.img4.acsta.net/pictures/19/08/27/14/55/2883843.jpg",
        type: "Anime",
        language: "VF & VO",
        genres: getAnimeGenres("beastars"),
      },
      {
        id: "black-clover",
        title: "Black Clover",
        imageUrl: "https://fr.web.img6.acsta.net/pictures/21/01/06/13/19/2738670.jpg",
        type: "Anime",
        language: "VF & VO",
        genres: getAnimeGenres("black-clover"),
      },
      {
        id: "bleach",
        title: "Bleach",
        imageUrl: "https://m.media-amazon.com/images/M/MV5BOWQwOWY5NTUtMjAyZi00YjQzLTkwODgtNmQwZjU1MGIzZDhjXkEyXkFqcGc@._V1_FMjpg_UX1000_.jpg",
        type: "Anime",
        language: "VF & VO",
        genres: getAnimeGenres("bleach"),
      },
      {
        id: "blue-lock",
        title: "Blue Lock",
        imageUrl: "https://fr.web.img4.acsta.net/pictures/22/10/07/09/03/4457121.jpg",
        type: "Anime",
        language: "VF & VO",
        genres: getAnimeGenres("blue-lock"),
      },
      {
        id: "code-geass",
        title: "Code Geass",
        imageUrl: "https://fr.web.img6.acsta.net/pictures/19/07/02/09/59/3177609.jpg",
        type: "Anime",
        language: "VF & VO",
        genres: getAnimeGenres("code-geass"),
      },
      {
        id: "cowboy-bebop",
        title: "Cowboy Bebop",
        imageUrl: "https://upload.wikimedia.org/wikipedia/en/a/a9/Cowboy_Bebop_key_visual.jpg",
        type: "Anime",
        language: "VF & VO",
        genres: getAnimeGenres("cowboy-bebop"),
      },
      {
        id: "darling-in-the-franxx",
        title: "Darling in the FranXX",
        imageUrl: "https://fr.web.img3.acsta.net/c_310_420/pictures/20/09/24/17/28/5295254.jpg",
        type: "Anime",
        language: "VF & VO",
        genres: getAnimeGenres("darling-in-the-franxx"),
      },
      {
        id: "dr-stone",
        title: "Dr. Stone",
        imageUrl: "https://fr.web.img6.acsta.net/img/74/2f/742fe88e2ca3d99868a47a70b329f436.jpg",
        type: "Anime",
        language: "VF & VO",
        genres: getAnimeGenres("dr-stone"),
      },
      {
        id: "fairy-tail",
        title: "Fairy Tail",
        imageUrl: "https://bdi.dlpdomain.com/serie/visuel/BDA_9407/1-M480x676.jpg",
        type: "Anime",
        language: "VF & VO",
        genres: getAnimeGenres("fairy-tail"),
      },
      {
        id: "food-wars",
        title: "Food Wars!",
        imageUrl: "https://m.media-amazon.com/images/I/81yFcrI4jaL._UF894,1000_QL80_.jpg",
        type: "Anime",
        language: "VF & VO",
        genres: getAnimeGenres("food-wars"),
      },
      {
        id: "free",
        title: "Free!",
        imageUrl: "https://m.media-amazon.com/images/M/MV5BNTEwMDhjY2UtZjczZC00ZjlkLWExMzEtMTE5NTQ4MTM5YzA4XkEyXkFqcGc@._V1_FMjpg_UX1000_.jpg",
        type: "Anime",
        language: "VF & VO",
        genres: getAnimeGenres("free"),
      },
      {
        id: "golden-kamui",
        title: "Golden Kamuy",
        imageUrl: "https://fr.web.img6.acsta.net/pictures/20/10/07/15/19/2217237.jpg",
        type: "Anime",
        language: "VF & VO",
        genres: getAnimeGenres("golden-kamui"),
      },
      {
        id: "haikyuu",
        title: "Haikyû!!",
        imageUrl: "https://fr.web.img3.acsta.net/c_310_420/pictures/19/09/27/13/12/0190127.jpg",
        type: "Anime",
        language: "VF & VO",
        genres: getAnimeGenres("haikyuu"),
      },
      {
        id: "hunter-x-hunter",
        title: "Hunter x Hunter",
        imageUrl: "https://m.media-amazon.com/images/M/MV5BYzYxOTlkYzctNGY2MC00MjNjLWIxOWMtY2QwYjcxZWIwMmEwXkEyXkFqcGc@._V1_.jpg",
        type: "Anime",
        language: "VF & VO",
        genres: getAnimeGenres("hunter-x-hunter"),
      },
      {
        id: "mob-psycho-100",
        title: "Mob Psycho 100",
        imageUrl: "https://fr.web.img2.acsta.net/pictures/20/11/12/14/25/3371142.jpg",
        type: "Anime",
        language: "VF & VO",
        genres: getAnimeGenres("mob-psycho-100"),
      },
      {
        id: "my-hero-academia",
        title: "My Hero Academia",
        imageUrl: "https://fr.web.img5.acsta.net/pictures/21/02/16/12/45/5319199.jpg",
        type: "Anime",
        language: "VF & VO",
        genres: getAnimeGenres("my-hero-academia"),
      },
      {
        id: "noragami",
        title: "Noragami",
        imageUrl: "https://fr.web.img6.acsta.net/pictures/19/07/09/16/38/4390834.jpg",
        type: "Anime",
        language: "VO",
        genres: getAnimeGenres("noragami"),
      },
      {
        id: "overlord",
        title: "Overlord",
        imageUrl: "https://fr.web.img6.acsta.net/img/c1/23/c12341dcf775f4148aa58469b59e030e.jpg",
        type: "Anime",
        language: "VF & VO",
        genres: getAnimeGenres("overlord"),
      },
      {
        id: "parasite",
        title: "Parasite",
        imageUrl: "https://fr.web.img4.acsta.net/c_310_420/pictures/19/07/12/10/57/3901004.jpg",
        type: "Anime",
        language: "VF & VO",
        genres: getAnimeGenres("parasite"),
      },
      {
        id: "promised-neverland",
        title: "The Promised Neverland",
        imageUrl: "https://fr.web.img4.acsta.net/pictures/20/02/26/09/12/3483516.jpg",
        type: "Anime",
        language: "VF & VO",
        genres: getAnimeGenres("promised-neverland"),
      },
      {
        id: "le-voyage-de-chihiro",
        title: "Le Voyage de Chihiro",
        imageUrl: "https://fr.web.img6.acsta.net/medias/nmedia/00/02/36/71/chihiro.jpg",
        type: "Anime",
        language: "VF & VO",
        genres: getAnimeGenres("le-voyage-de-chihiro"),
      },
      {
        id: "steins-gate",
        title: "Steins;Gate",
        imageUrl: "https://m.media-amazon.com/images/M/MV5BZjI1YjZiMDUtZTI3MC00YTA5LWIzMmMtZmQ0NTZiYWM4NTYwXkEyXkFqcGc@._V1_FMjpg_UX1000_.jpg",
        type: "Anime",
        language: "VF & VO",
        genres: getAnimeGenres("steins-gate"),
      },
      {
        id: "tensei-shitara-slime-datta-ken",
        title: "Moi, quand je me réincarne en Slime",
        imageUrl: "https://m.media-amazon.com/images/M/MV5BNWU3OTRlNWMtZGQyOC00YzJhLWIyNjctYmI2YzgyZTQ3ZDNmXkEyXkFqcGc@._V1_.jpg",
        type: "Anime",
        language: "VF & VO",
        genres: getAnimeGenres("tensei-shitara-slime-datta-ken"),
      },
      {
        id: "tokyo-revengers",
        title: "Tokyo Revengers",
        imageUrl: "https://fr.web.img2.acsta.net/pictures/21/06/30/12/00/4012840.jpg",
        type: "Anime",
        language: "VF & VO",
        genres: getAnimeGenres("tokyo-revengers"),
      },
      {
        id: "violet-evergarden",
        title: "Violet Evergarden",
        imageUrl: "https://fr.web.img5.acsta.net/pictures/19/07/08/14/28/2218608.jpg",
        type: "Anime",
        language: "VF & VO",
        genres: getAnimeGenres("violet-evergarden"),
      },
      {
        id: "bungou-stray-dogs",
        title: "Bungo Stray Dogs",
        imageUrl: "https://fr.web.img6.acsta.net/pictures/19/07/02/17/25/0852049.jpg",
        type: "Anime",
        language: "VF & VO",
        genres: getAnimeGenres("bungou-stray-dogs"),
      },
      {
        id: "elfen-lied",
        title: "Elfen Lied",
        imageUrl: "https://fr.web.img5.acsta.net/pictures/21/11/24/08/29/4692226.jpg",
        type: "Anime",
        language: "VF & VO",
        genres: getAnimeGenres("elfen-lied"),
      },
      {
        id: "made-in-abyss",
        title: "Made in Abyss",
        imageUrl: "https://m.media-amazon.com/images/M/MV5BZjM4ODA5YTktNjliMC00NzI5LTk3ZTctZWYyYWEyNTJhMmQzXkEyXkFqcGc@._V1_.jpg",
        type: "Anime",
        language: "VF & VO",
        genres: getAnimeGenres("made-in-abyss"),
      },
      {
        id: "nisekoi",
        title: "Nisekoi",
        imageUrl: "https://images.justwatch.com/poster/240768233/s718/nisekoi.jpg",
        type: "Anime",
        language: "VF & VO",
        genres: getAnimeGenres("nisekoi"),
      },
      {
        id: "one-punch-man",
        title: "One Punch Man",
        imageUrl: "https://fr.web.img4.acsta.net/c_310_420/pictures/17/02/27/17/41/046707.jpg",
        type: "Anime",
        language: "VF & VO",
        genres: getAnimeGenres("one-punch-man"),
      },
      {
        id: "seven-deadly-sins",
        title: "The Seven Deadly Sins",
        imageUrl: "https://bdi.dlpdomain.com/serie/visuel/BDA_14940/1-M480x680.jpg",
        type: "Anime",
        language: "VF & VO",
        genres: getAnimeGenres("seven-deadly-sins"),
      },
      {
        id: "the-rising-of-the-shield-hero",
        title: "The Rising of the Shield Hero",
        imageUrl: "https://fr.web.img2.acsta.net/pictures/23/09/14/17/04/0681417.jpg",
        type: "Anime",
        language: "VF & VO",
        genres: getAnimeGenres("the-rising-of-the-shield-hero"),
      },
      {
        id: "jojo-bizarre-adventure",
        title: "JoJo's Bizarre Adventure",
        imageUrl: "https://fr.web.img3.acsta.net/c_310_420/pictures/20/03/10/12/07/4001550.jpg",
        type: "Anime",
        language: "VF & VO",
        genres: getAnimeGenres("jojo-bizarre-adventure"),
      }
];

// Fonction pour obtenir l'image d'un anime - priorité au catalogue, puis animeData
export const getAnimeImage = (animeId: string): string => {
  // D'abord chercher dans le catalogue statique
  const catalogueAnime = animes.find(a => a.id === animeId);
  if (catalogueAnime?.imageUrl) {
    return catalogueAnime.imageUrl;
  }
  
  // Si pas dans le catalogue, chercher dans animeData
  const animeData = animeDataList.find(a => a.id === animeId);
  if (animeData?.imageUrl) {
    return animeData.imageUrl;
  }
  
  // Image par défaut si aucune trouvée
  return "https://m.media-amazon.com/images/M/MV5BM2ZiZTk1ODgtMTZkNS00NTYxLWIxZTUtNWExZGYwZTRjODViXkEyXkFqcGdeQXVyMTE2MzA3MDM@._V1_.jpg";
};

export const genres = [
  "Action", "Adolescence", "Aliens / Extra-terrestres", "Amitié", "Amour", "Apocalypse", "Art", "Arts martiaux", "Assassinat", "Autre monde",
  "Aventure", "Combats", "Comédie", "Crime", "Cyberpunk", "Danse", "Démons", "Détective", "Donghua", "Drame",
  "Ecchi", "École", "Enquête", "Famille", "Fantastique", "Fantasy", "Fantômes", "Futur", "Gastronomie", "Ghibli",
  "Guerre", "Harcèlement", "Harem", "Harem inversé", "Histoire", "Historique", "Horreur", "Isekai", "Jeunesse", "Jeux",
  "Jeux vidéo", "Josei", "Journalisme", "Mafia", "Magical girl", "Magie", "Maladie", "Mariage", "Mature",
  "Mechas", "Médiéval", "Militaire", "Monde virtuel", "Monstres", "Musique", "Mystère", "Nekketsu", "Ninjas", "Nostalgie",
  "Paranormal", "Philosophie", "Pirates", "Police", "Politique", "Post-apocalyptique", "Pouvoirs psychiques", "Préhistoire", "Prison", "Psychologique",
  "Quotidien", "Religion", "Réincarnation / Transmigration", "Romance", "Samouraïs", "School Life", "Science-Fantasy", "Science-fiction", "Scientifique", "Seinen",
  "Shôjo", "Shôjo-Ai", "Shônen", "Shônen-Ai", "Slice of Life", "Société", "Sport", "Super pouvoirs", "Super-héros", "Surnaturel",
  "Survie", "Survival game", "Technologies", "Thriller", "Tournois", "Travail", "Vampires", "Vengeance", "Voyage", "Voyage temporel",
  "Webcomic", "Yakuza", "Yaoi", "Yokai", "Yuri"
];
